version: '3'

volumes:
  postgres_data:
  static_value:
  media_value:

services:
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
  backend:
    image: tyulyagin/foodgram_backend:latest
    restart: always
    volumes:
      - static_value:/code/static_backend/
      - media_value:/code/media/
    depends_on:
      - db
    env_file:
      - ./.env
  frontend:
    image: tyulyagin/foodgram_frontend:latest
    volumes:
      - ../frontend/:/app/result_build/
    depends_on:
      - backend
  nginx:
    image: nginx:1.19.3
    ports:
      - 8001:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - /docs/:/usr/share/nginx/html/api/docs/
      - static_value:/var/html/static_backend/
      - media_value:/var/html/media/
    restart: always
    depends_on:
      - backend
      - frontend