version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    container_name: foodgram_db
    env_file: .env
    image: postgres:13.11
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: always

  backend:
    container_name: foodgram_backend
    env_file: .env
    image: ${DOCKER_LOGIN}/foodgram_backend
    volumes:
      - static:/static
      - media:/app/media
    depends_on:
      - db
    restart: always  

  frontend:
    container_name: foodgram_frontend
    env_file: .env
    image: ${DOCKER_LOGIN}/foodgram_frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static:/static

  gateway:
    container_name: foodgram_gateway
    env_file: .env
    image: ${DOCKER_LOGIN}/foodgram_gateway
    volumes:
      - static:/static
      - media:/media
    ports:
      - ${NGINX_PORT}:80
    depends_on:
      - backend
    restart: always